import React from "react";
import { Calendar } from "lucide-react";

export default function ExperienceSection({ experiences = [] }) {
  return (
    <div className="space-y-6">
      <div className="border-b border-border pb-3">
        <h2 className="text-[24px] font-heading font-semibold text-foreground">
          Professional Experience
        </h2>
      </div>

      <div className="space-y-8">
        {experiences.length > 0 ? (
          experiences.map((exp, index) => (
            <div key={index} className="space-y-3">
              {/* Header Company Details */}
              <div className="flex flex-col md:flex-row md:items-center justify-between gap-1">
                <div>
                  <h3 className="text-[20px] font-heading font-semibold text-foreground">
                    {exp.role}
                  </h3>
                  <p className="text-[16px] font-sans text-primary/90 font-medium mt-0.5">
                    {exp.company}
                  </p>
                </div>
                <div className="flex items-center gap-1.5 text-[14px] font-sans text-muted-foreground">
                  <Calendar className="w-4 h-4 text-muted-foreground/60" />
                  {exp.duration || "Present"}
                </div>
              </div>

              {/* Achievements generated by AI */}
              <ul className="list-disc list-outside pl-4 space-y-2 text-[14px] md:text-[16px] font-sans text-muted-foreground">
                {exp.achievements?.map((achievement, actIndex) => (
                  <li key={actIndex} className="leading-relaxed">
                    {achievement}
                  </li>
                ))}
              </ul>
            </div>
          ))
        ) : (
          <p className="text-[14px] font-sans text-muted-foreground">
            Belum ada riwayat kerja yang teranalisis.
          </p>
        )}
      </div>
    </div>
  );
}
